In [4]:
import  pandas as pd 
import numpy as np

In [5]:
# read_csv() used to read csv file 

df = pd.read_csv('youtube.csv' , encoding='latin1')
sub = df[['subscribers']  ]
sub.head()

   subscribers
0  245000000.0
1  170000000.0
2  166000000.0
3  162000000.0
4  159000000.0

In [6]:
sub.mean()

subscribers    2.319501e+07
dtype: float64

In [7]:
sub.sum()

subscribers    2.326460e+10
dtype: float64

In [8]:
sub.sort_values()

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

In [ ]:
print(sub.max())
print(sub.min())
print(sub.median())

245000000.0
12300000.0
17700000.0

In [ ]:
cols = df[["Youtuber" , 'subscribers' ,"video views" ]]

cols

                        Youtuber  subscribers   video views
0                       T-Series  245000000.0  2.280000e+11
1                 YouTube Movies  170000000.0  0.000000e+00
2                        MrBeast  166000000.0  2.836884e+10
3     Cocomelon - Nursery Rhymes  162000000.0  1.640000e+11
4                      SET India  159000000.0  1.480000e+11
...                          ...          ...           ...
1001                    The Dodo   14200000.0  9.964117e+09
1002            Supercar Blondie   14100000.0  5.405563e+09
1003        Just For Laughs Gags   13300000.0  7.406629e+09
1004            Kabita's Kitchen   13300000.0  2.831276e+09
1005                  BanderitaX   13300000.0  4.129249e+09

[1006 rows x 3 columns]

In [9]:

one_col = pd.read_csv('youtube.csv' , encoding='latin1' )
one_col['Youtuber'].head()

0                      T-Series
1                YouTube Movies
2                       MrBeast
3    Cocomelon - Nursery Rhymes
4                     SET India
Name: Youtuber, dtype: str

In [ ]:
one_col[['Youtuber' , 'subscribers']].tail()

(one_col.sample())

,rank,Youtuber,subscribers,video views,category,Title,uploads,Country of origin,Country,Abbreviation,...,subscribers_for_last_30_days,created_year,created_month,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
521,522,Taarak Mehta Ka Ooltah Chashmah,17300000.0,1.137174e+10,Entertainment,Taarak Mehta Ka Ooltah Chashmah,4778,India,India,IN,...,300000.0,2014.0,Aug,4.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.96288

In [ ]:
one_col['created_year'].value_counts()

,rank,Youtuber,subscribers,video views,category,Title,uploads,Country of origin,Country,Abbreviation,...,subscribers_for_last_30_days,created_year,created_month,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
101,102,YouTube,36300000.0,3.010785e+09,News & Politics,YouTube,744,United States,United States,US,...,300000.0,1970.0,Jan,1.0,88.2,328239523.0,14.7,270663028.0,37.09024,-95.712891

In [48]:
one_col[['category' , 'Youtuber' , 'subscribers']].sort_values(by='subscribers' , ascending=False)

,category,Youtuber,subscribers
0,Music,T-Series,245000000.0
1,Film & Animation,YouTube Movies,170000000.0
2,Entertainment,MrBeast,166000000.0
3,Education,Cocomelon - Nursery Rhymes,162000000.0
4,Shows,SET India,159000000.0
...,...,...,...
994,Comedy,Make Joke Of,12300000.0
990,Sports,Natan por Aï¿,12300000.0
978,Entertainment,Heidi and Zidane HZHtube,NaN
979,Gaming,DaniRep | +6 Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï,NaN
980,Film & Animation,Zee Kids,NaN

In [44]:
# sorting 

one_col['created_year'].sort_values(ascending=True)

101    1970.0
987    2005.0
51     2005.0
539    2005.0
519    2005.0
        ...
236       NaN
468       NaN
508       NaN
735       NaN
762       NaN
Name: created_year, Length: 1006, dtype: float64

In [50]:
def format_subscribers(x):
    if x >= 1_000_000_000:
        return f"{x / 1_000_000_000:.1f}B"
    elif x >= 1_000_000:
        return f"{x / 1_000_000:.1f}M"
    elif x >= 1_000:
        return f"{x / 1_000:.1f}K"
    else:
        return str(x)

In [52]:
df["subscribers_readable"] = df["subscribers"].apply(format_subscribers)

df

,rank,Youtuber,subscribers,video views,category,Title,uploads,Country of origin,Country,Abbreviation,...,created_year,created_month,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude,subscribers_readable
0,1,T-Series,245000000.0,2.280000e+11,Music,T-Series,20082,India,india,IN,...,2006.0,Mar,13.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880,245.0M
1,2,YouTube Movies,170000000.0,0.000000e+00,Film & Animation,youtubemovies,1,United States,United States,US,...,2006.0,NaN,5.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891,170.0M
2,3,MrBeast,166000000.0,2.836884e+10,Entertainment,MrBeast,741,United States,United States,US,...,2012.0,Feb,20.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891,166.0M
3,4,Cocomelon - Nursery Rhymes,162000000.0,1.640000e+11,Education,Cocomelon - Nursery Rhymes,966,United States,United States,US,...,2006.0,Sep,1.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891,162.0M
4,5,SET India,159000000.0,1.480000e+11,Shows,SET India,116536,India,India,IN,...,2006.0,Sep,20.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880,159.0M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,779,The Dodo,14200000.0,9.964117e+09,Pets & Animals,Dorukhan Gï¿½ï¿½ï,8,NaN,NaN,NaN,...,2006.0,Jun,14.0,NaN,NaN,NaN,NaN,NaN,NaN,14.2M
1002,787,Supercar Blondie,14100000.0,5.405563e+09,Autos & Vehicles,Supercar Blondie,855,United Arab Emirates,United Arab Emirates,AE,...,2007.0,Sep,12.0,36.8,9.770529e+06,2.35,8479744.0,23.424076,53.847818,14.1M
1003,871,Just For Laughs Gags,13300000.0,7.406629e+09,Comedy,Just For Laughs Gags,6916,United States,United States,US,...,2007.0,Jan,14.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891,13.3M
1004,872,Kabita's Kitchen,13300000.0,2.831276e+09,Howto & Style,Kabita's Kitchen,1489,India,India,IN,...,2014.0,Oct,7.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880,13.3M
1005,873,BanderitaX,13300000.0,4.129249e+09,Gaming,BanderitaX,1640,Saudi Arabia,Saudi Arabia,SA,...,2013.0,Aug,20.0,68.0,3.426853e+07,5.93,28807838.0,23.885942,45.079162,13.3M

In [59]:
df[['Youtuber' ,'subscribers_readable' , 'created_year','subscribers']].head().sort_values(by='subscribers' , ascending=False)

                     Youtuber subscribers_readable  created_year  subscribers
0                    T-Series               245.0M        2006.0  245000000.0
1              YouTube Movies               170.0M        2006.0  170000000.0
2                     MrBeast               166.0M        2012.0  166000000.0
3  Cocomelon - Nursery Rhymes               162.0M        2006.0  162000000.0
4                   SET India               159.0M        2006.0  159000000.0

In [72]:
df = pd.read_csv('youtube.csv' , encoding='latin1')
df["subscribers_readable"] = df["subscribers"].apply(format_subscribers)
df['subscribers_readable']
dir(df)

['Abbreviation',
 'Country',
 'Latitude',
 'Longitude',
 'Population',
 'T',
 'Title',
 'Urban_population',
 'Youtuber',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_select_dtypes_indices',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'category',
 'channel_type',
 'channel_type_rank',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'country_rank',
 'cov',
 'created_date',
 'created_month',
 'created_year',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'highest_monthly_earnings',
 'highest_yearly_earnings',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'loc',
 'lowest_monthly_earnings',
 'lowest_yearly_earnings',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subscribers',
 'subscribers_for_last_30_days',
 'subscribers_readable',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'uploads',
 'value_counts',
 'values',
 'var',
 'video_views_for_the_last_30_days',
 'video_views_rank',
 'where',
 'xs']

In [75]:

type(df)

pandas.DataFrame